# Generated by Django 3.2.20 on 2023-09-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='shipping_charge',
            new_name='TCS',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='taxamount',
        ),
        migrations.RemoveField(
            model_name='salescreditnote',
            name='description',
        ),
        migrations.RemoveField(
            model_name='salescreditnote',
            name='shipping_charge',
        ),
        migrations.AddField(
            model_name='invoice',
            name='gstin',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='salescreditnote',
            name='gstin',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employeeloan',
            name='File',
            field=models.FileField(blank=True, default='', null=True, upload_to='loanfile'),
        ),
    ]
