# Generated by Django 3.2.20 on 2023-09-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challan',
            name='adjustment',
            field=models.IntegerField(default=0),
        ),
    ]
