# Generated by Django 3.2.20 on 2023-09-13 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_challan_adjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='adjustment',
            field=models.FloatField(default=0),
        ),
    ]
