# Generated by Django 3.2.20 on 2023-09-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20230905_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeloan',
            name='action',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
