# Generated by Django 3.2.20 on 2023-09-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_employeeloan_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='TCS',
            new_name='shipping_charge',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='gstin',
        ),
        migrations.RemoveField(
            model_name='salescreditnote',
            name='gstin',
        ),
        migrations.AddField(
            model_name='invoice',
            name='taxamount',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salescreditnote',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salescreditnote',
            name='shipping_charge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
