# Generated by Django 3.2.20 on 2023-09-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_challan_adjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill',
            name='balance_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='paid_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='payment_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='ship_charge',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='total_discount',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='vendor_mail',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill_item',
            name='discount',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='balance_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='paid_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='ship_charge',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='total_discount',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor_mail',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder_item',
            name='discount',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='attachment',
            field=models.ImageField(null=True, upload_to='vendor-files/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='opening_balance_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Billed', 'Billed')], default='Billed', max_length=150),
        ),
    ]
