# Generated by Django 4.2.3 on 2023-09-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0004_auto_20230907_0935"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockadjust",
            name="status",
            field=models.CharField(default="Draft", max_length=100),
        ),
    ]
