# Generated by Django 3.2.20 on 2023-09-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20230918_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjust',
            name='comment',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='stockadjust',
            name='status',
            field=models.CharField(default='Draft', max_length=100),
        ),
    ]
