# Generated by Django 3.2.20 on 2023-09-21 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20230919_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='recurring_bill',
            fields=[
                ('rbillid', models.AutoField(primary_key=True, serialize=False, verbose_name='rid')),
                ('billno', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_name', models.CharField(blank=True, max_length=100, null=True)),
                ('source_supply', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('repeat_every', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_total', models.FloatField(blank=True, null=True)),
                ('igst', models.FloatField(blank=True, null=True)),
                ('cgst', models.FloatField(blank=True, null=True)),
                ('sgst', models.FloatField(blank=True, null=True)),
                ('tax_amount', models.FloatField(blank=True, null=True)),
                ('shipping_charge', models.FloatField(blank=True, null=True)),
                ('adjustment', models.FloatField(blank=True, default=0, null=True)),
                ('grand_total', models.FloatField(blank=True, null=True)),
                ('note', models.CharField(max_length=255, null=True)),
                ('paid_amount', models.FloatField(default=0, max_length=100, null=True)),
                ('balance', models.FloatField(max_length=100, null=True)),
                ('file', models.FileField(default='default.png', upload_to='purchase/rbill')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Billed', 'Billed')], default='Draft', max_length=150)),
                ('cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
        migrations.CreateModel(
            name='repeatevery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeat', models.CharField(blank=True, max_length=100, null=True)),
                ('cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
        migrations.CreateModel(
            name='recurringbill_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100, null=True)),
                ('hsn', models.CharField(max_length=100, null=True)),
                ('qty', models.IntegerField(default=0, null=True)),
                ('price', models.CharField(max_length=100, null=True)),
                ('total', models.IntegerField(default=0, null=True)),
                ('discount', models.CharField(max_length=100, null=True)),
                ('tax', models.CharField(max_length=100, null=True)),
                ('bill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.recurring_bill')),
                ('cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
    ]
