# Generated by Django 4.2.3 on 2023-09-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0005_alter_stockadjust_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockadjust",
            name="comment",
            field=models.CharField(default="", max_length=500),
        ),
    ]
